{{- if and .Values.manifests.configmap_bin .Values.deployment.postgresql }}
{{- $envAll := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" $envAll.Release.Name "bin" }}
data:
{{- if .Values.images.local_registry.active }}
  image-repo-sync.sh: |
{{- include "helm-toolkit.scripts.image_repo_sync" . | indent 4 }}
{{- end }}

{{- if .Values.bootstrap.enabled }}
  bootstrap.sh: |
{{ tuple "bin/_bootstrap.sh.tpl" . | include "helm-toolkit.utils.template" | indent 4 }}
{{- end }}

  start.sh: |
{{ tuple "bin/_start.sh.tpl" . | include  "helm-toolkit.utils.template" | indent 4 }}

  postgresql-utility-rootwrap: |
{{ tuple "bin/utility/_postgresql-utility-rootwrap.tpl" . | include  "helm-toolkit.utils.template" | indent 4 }}

  nccli: |
{{ tuple "bin/utility/_nccli.tpl" . | include  "helm-toolkit.utils.template" | indent 4 }}

  osd-maintenance: |
{{ tuple "bin/utility/_osd-maintenance.tpl" . | include  "helm-toolkit.utils.template" | indent 4 }}

  rbd_pv: |
{{ tuple "bin/utility/_rbd_pv.tpl" . | include  "helm-toolkit.utils.template" | indent 4 }}

{{- end }}
